### ISSUE TITLE
Dashboard Grow Climate chart not updating

### ISSUE THREAD

**Issue by jkissner** [fruxefarms/FruxePi#19] opened 2019-03-06 17:40 UTC
The chart is stuck with old data.

**Comment by fruxefarms** [comment] 2019-03-07 20:16
Hmm, my immediate guess would be to check the database settings in the `/var/www/html/actions/fruxepi-chart.py` if you have changed them. 

Also, there is a CRON job running this task every hour. Perhaps check if that is updating.
`0 * * * * python /var/www/html/actions/fruxepi-chart.py ` 

Definite area for improvement with respect to the charts and how that is handled in the database. This was just a lazy fix if I recall and I'm not a fan of how this works at the moment either.

**Comment by dcaud** [comment] 2019-03-16 17:51
I too am having the issue of the chart not updating (nor the temp and humidity values in the banner of the dashboard).

When I go to http://<my.ip>/technical/climate and click `Test Sensor` all appears good. I get this message: `All good - Climate Sensor Operational!`

Should I check database settings by doing this:

`sudo docker exec -it frxpi-APACHE bash`
`nano /var/www/html/actions/fruxepi-chart.py`

If so, here are the database settings:

```
# Functions
# fetchData - Fetch from sql string
def fetchData(sql):

    # Connect to the database
    connection = pymysql.connect(host='localhost',
                                 user='frxpi',
                                 password='password',
                                 db='frx_db',
                                 charset='utf8mb4',
                                 cursorclass=pymysql.cursors.DictCursor)
```


Also, I'm not exactly sure how to check if the cronjob is running. I tried this:

`sudo docker exec -it frxpi-APACHE bash`

Then:
`sudo crontab -l`

Which returned this:

`no crontab for root`

Is this the correct cron file?
`sudo docker exec -it frxpi-APACHE bash`
`nano /var/spool/cron/crontabs/www-data`

**Comment by dcaud** [comment] 2019-03-16 18:19
I got the dashboard header data to update by changing the cron file, like this (If I remember correctly):

`sudo docker exec -it frxpi-APACHE bash`
`crontab -e`

And then pasting this at the bottom of that file:

```
# FruxePi
* * * * * sudo /var/www/html/actions/fruxepi.py update -growdata
* * * * * sudo /var/www/html/actions/fruxepi-chart.py
0 1 * * * sudo /var/www/html/actions/fruxepi.py maint -cleanup
#* * * * * sudo /var/www/html/actions/fruxepi.py camera -crop
#0 1 * * * sudo /var/www/html/actions/fruxepi.py lights -ON 15
#0 1 * * * sudo /var/www/html/actions/fruxepi.py lights -OFF 15
#0 * * * * sudo /var/www/html/actions/fruxepi.py fan -RUN 17 10
#11 11 * * * sudo /var/www/html/actions/fruxepi.py pump -RUN 15 5
```

Notice that I changed the second line to update every minute, because I thought that would help with troubleshooting.

However, I still haven't got the chart to update.

**Comment by fruxefarms** [comment] 2019-03-16 19:15
CRON is still an issue, and I apologize. I have success with it but every so often it doesn’t deploy correctly. Will keep working on it. You need to edit the www-data user’s cron. “Sudo crontab -u www-data -e” also restart cron after every edit. For some reason that is sticking also. Will have an update soon.

**Comment by fruxefarms** [comment] 2019-03-17 23:35
I think this has been sorted out in the latest commit. There was a wrong database hostname in the file that was not "dockerized".

**Comment by dcaud** [comment] 2019-03-18 19:06
My chart still isn't updating.

Using v0.2-BETA -- just installed, then waited for an hour to pass. The chart shows data from 2018.

The dashboard header is showing the current temp and humidity (well, I think it samples those values every minute), which is good news.

**Comment by fruxefarms** [comment] 2019-03-19 22:09
This was perhaps a permissions issue that needs to be addressed. In the meantime, I believe this will fix the chart issue:
```
sudo docker exec -it frxpi-APACHE /bin/bash -c 'chmod +x /var/www/html/actions/fruxepi-chart.py;'
```

**Comment by dcaud** [comment] 2019-03-20 06:07
No luck here. Still not updating as far as I can tell. 

I think you made significant changes since you left the instructions above about permissions, and so the note above does not currently apply. However, just in case, here is what I got when following the instructions:

```
pi@raspberrypi:~ $ sudo docker exec -it frxpi-APACHE /bin/bash -c 'chmod +x /var/www/html/actions/fruxepi-chart.py;'

chmod: cannot access ‘/var/www/html/actions/fruxepi-chart.py’: No such file or directory
```

**Comment by dcaud** [comment] 2019-03-20 06:39
I can confirm that the climate_history table in_frx_db is not updating, but that when I insert new data into the database from the command line, the chart updates. Therefore, the problem seems to be about writing to the database. 

For example:

`sudo docker exec -it frxpi-MYSQL bash`

`sudo mysql -u root -p`

Then:

```
CREATE TEMPORARY TABLE temp_table ENGINE=MEMORY;

SELECT * FROM climate_history WHERE id=24;
UPDATE temp_table SET id=NULL, date_time='2019-02-18 23:00:00', temperature='45'; /* Update other values at will. */

INSERT INTO climate_history SELECT * FROM temp_table;
DROP TABLE temp_table;
```
Adds a new row...and the new value is displayed in the chart.

**Comment by dcaud** [comment] 2019-03-20 06:48
I think we are reading from climate_history but writing to grow_data.

**Comment by dcaud** [comment] 2019-03-20 07:04
Yep, I think here is a way to make something update:

Find and replace "climate_history" with "grow_data" in /var/www/html/application/models/Dashboard_model.php

I see the chart update with that change in code. However, maybe the goal should be to figure out how to write appropriately to "climate_history" -- an average of each hour's worth of temp and humidity?

Maybe the way to do this is via something that changes the crontab file from:
`* * * * * sudo /var/www/html/actions/fruxepi.py update -growdata`
to
`* * * * * sudo /var/www/html/actions/fruxepi.py update -chart`? (which I see you've already done)

But I don't really know.

**Comment by fruxefarms** [comment] 2019-03-20 11:03
You are right, it was calling the missing `fruxepi-chart.py` file and wasn't reflected in the crontab file. I merged the two after I sent you that message. My apologies! I changed the crontab file.

**Closed as completed** 2019-03-22 08:26 UTC
Labels: bug
